plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "nanashiBlog"
email: wangjy.nanashi@gmail.com
description: ""
github:
  username: eccentric-w
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
comment:
    repo: blog
    client_id: 914339edf5eb3abf1c9b
    client_secret: 5168dc088effb9684810f54daa3672a5961c697c

url: "https://eccentric-w.github.io/blog"
imgrepo: "https://eccentric-w.github.io/blog/static/img"


